stages:
  build_corpus:
    cmd: python src/stages/build_corpus.py data/raw/example_context.txt data/processed/corpus.pkl
    deps:
      - src/stages/build_corpus.py
      - data/raw/example_context.txt
    outs:
      - data/processed/corpus.pkl

  build_embedder: #https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v1
    cmd: python src/stages/build_embedder.py "sentence-transformers/distiluse-base-multilingual-cased-v1" data/processed/embedder.pkl
    deps:
      - src/stages/build_embedder.py
    outs:
      - data/processed/embedder.pkl

  build_vectorstore:
    cmd: python src/stages/build_vectorstore.py data/processed/corpus.pkl data/processed/embedder.pkl data/processed/chroma
    deps:
      - src/stages/build_vectorstore.py
      - data/processed/corpus.pkl
      - data/processed/embedder.pkl
    outs:
      - data/processed/chroma

  #load_vectorstore:
  #  cmd: python src/stages/load_vectorstore.py data/processed/chroma data/processed/embedder.pkl "Wo braucht es einen agenten?"
  #  deps:
  #    - src/stages/load_vectorstore.py
  #    - data/processed/chroma
  #    - data/processed/embedder.pkl

  build_ft_dataset: #https://huggingface.co/datasets/deepset/germanquad
    cmd: python src/stages/build_ft_dataset.py data/processed/ft_dataset.hf
    deps:
      - src/stages/build_ft_dataset.py
    outs:
      - data/processed/ft_dataset.hf

  train_llm: 
    cmd: python src/stages/train_llm.py data/processed/ft_dataset.hf
    deps:
      - src/stages/train_llm.py
      - data/processed/ft_dataset.hf