stages:
  build_corpus:
    cmd: python src/stages/build_corpus.py data/raw/example_context.txt data/processed/corpus.pkl
    deps:
      - src/stages/build_corpus.py
      - data/raw/example_context.txt
    outs:
      - data/processed/corpus.pkl

  build_embedder:
    cmd: python src/stages/build_embedder.py data/processed/distilbert-base-tas-b-embedder.pkl
    deps:
      - src/stages/build_embedder.py
    outs:
      - data/processed/distilbert-base-tas-b-embedder.pkl