stages:
  build_corpus:
    cmd: python src/stages/build_corpus.py data/raw/spaces data/processed/corpus.jsonl
    deps:
      - src/stages/build_corpus.py
      - data/raw/spaces
    outs:
      - data/processed/corpus.jsonl

  build_embedder: #https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v1
    cmd: python src/stages/build_embedder.py "sentence-transformers/distiluse-base-multilingual-cased-v1" data/processed/embedder.pkl
    deps:
      - src/stages/build_embedder.py
    outs:
      - data/processed/embedder.pkl

  build_vectorstore:
    cmd: python src/stages/build_vectorstore.py data/processed/corpus.jsonl data/processed/embedder.pkl data/processed/chroma
    deps:
      - src/stages/build_vectorstore.py
      - data/processed/corpus.jsonl
      - data/processed/embedder.pkl
    outs:
      - data/processed/chroma

  load_vectorstore:
    cmd: python src/stages/load_vectorstore.py data/processed/chroma data/processed/embedder.pkl "Was weisst du zum  Modul Vertiefende Themen der Analysis?" --strategy selfquery
    deps:
      - src/stages/load_vectorstore.py
      - data/processed/chroma
      - data/processed/embedder.pkl

  build_ft_dataset: #https://huggingface.co/datasets/deepset/germanquad
    cmd: python src/stages/build_ft_dataset.py build_tf_dataset data/processed/ft_dataset.hf
    deps:
      - src/stages/build_ft_dataset.py
    params:
      - build_tf_dataset
    outs:
      - data/processed/ft_dataset.hf

  build_ft_dataset_gpt_context_add_source:
    cmd: python src/stages/build_ft_dataset_gpt_context_add_source.py data/processed/ft_dataset.hf data/processed/ft_dataset_source_added.hf
    deps:
      - data/processed/ft_dataset.hf
      - src/stages/build_ft_dataset_gpt_context_add_source.py
    outs:
      - data/processed/ft_dataset_source_added.hf

  build_ft_dataset_gpt_answer:
    cmd: python src/stages/build_ft_dataset_gpt_answer.py data/processed/ft_dataset_source_added.hf data/processed/ft_dataset_abstractive.hf
    deps:
      - data/processed/ft_dataset_source_added.hf
      - src/stages/build_ft_dataset_gpt_answer.py
    outs:
      - data/processed/ft_dataset_abstractive.hf

  train_llm:
    cmd: python src/stages/train_llm.py train_llm data/processed/test_data.hf ./data/models/llama2-qa-fine-tuned
    deps:
      - src/stages/train_llm.py
      - data/processed/test_data.hf
    params:
      - train_llm
    outs:
      - ./data/models/llama2-qa-fine-tuned

  load_llm:
    cmd: python src/stages/load_llm.py inference ./data/models/llama2-qa-fine-tuned ./data/raw/example_context.json "Was ist DVC?"
    deps:
      - src/stages/load_llm.py
      - ./data/models/llama2-qa-fine-tuned
      - ./data/raw/example_context.json
    params:
      - inference

  eval_retrieval_question_gen:
    cmd: python src/stages/eval_retrieval_question_gen.py data/processed/chroma data/processed/embedder.pkl data/processed/eval_retrieval_questions.parquet
    deps:
      - src/stages/eval_retrieval_question_gen.py
      - data/processed/chroma
      - data/processed/embedder.pkl
    outs:
      - data/processed/eval_retrieval_questions.parquet

#  push_model_to_hub:
#    cmd: python src/stages/push_model_to_hub.py inference ./data/models/llama2-qa-fine-tuned "nlpchallenges/chatbot-qa-path"
#    deps:
#      - src/stages/push_model_to_hub.py
#      - ./data/models/llama2-qa-fine-tuned
#    params:
#      - inference
