stages:
  build_corpus:
    cmd: python src/stages/build_corpus.py data/raw/spaces data/processed/corpus.jsonl
    deps:
      - src/stages/build_corpus.py
      - data/raw/spaces
    outs:
      - data/processed/corpus.jsonl

  build_embedder: #https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v1
    cmd: python src/stages/build_embedder.py "sentence-transformers/distiluse-base-multilingual-cased-v1" data/processed/embedder.pkl
    deps:
      - src/stages/build_embedder.py
    outs:
      - data/processed/embedder.pkl

  build_vectorstore:
    cmd: python src/stages/build_vectorstore.py data/processed/corpus.jsonl data/processed/embedder.pkl data/processed/chroma
    deps:
      - src/stages/build_vectorstore.py
      - data/processed/corpus.jsonl
      - data/processed/embedder.pkl
    outs:
      - data/processed/chroma

  load_vectorstore:
    cmd: python src/stages/load_vectorstore.py data/processed/chroma data/processed/embedder.pkl "Was weisst du zum  Modul Vertiefende Themen der Analysis?" --strategy selfquery
    deps:
      - src/stages/load_vectorstore.py
      - data/processed/chroma
      - data/processed/embedder.pkl

  build_ft_dataset: #https://huggingface.co/datasets/deepset/germanquad
    cmd: python src/stages/build_ft_dataset.py build_tf_dataset data/processed/ft_dataset.hf
    deps:
      - src/stages/build_ft_dataset.py
    params:
      - build_tf_dataset
    outs:
      - data/processed/ft_dataset.hf

  train_llm:
    cmd: python src/stages/train_llm.py train_llm data/processed/ft_dataset.hf ./data/models/llama2-qa-fine-tuned
    deps:
      - src/stages/train_llm.py
      - data/processed/ft_dataset.hf
    params:
      - train_llm
    outs:
      - ./data/models/llama2-qa-fine-tuned

  load_llm:
    cmd: python src/stages/load_llm.py load_llm ./data/models/llama2-qa-fine-tuned "Auf was spielte Python an?" "Die Sprache wurde Anfang der 1990er Jahre von Guido van Rossum am Centrum Wiskunde & Informatica in Amsterdam als Nachfolger für die Programmier-Lehrsprache ABC entwickelt und war ursprünglich für das verteilte Betriebssystem Amoeba gedacht. Der Name geht nicht, wie das Logo vermuten lässt, auf die gleichnamige Schlangengattung Python zurück, sondern bezog sich ursprünglich auf die englische Komikergruppe Monty Python. In der Dokumentation finden sich daher auch einige Anspielungen auf Sketche aus dem Flying Circus. Trotzdem etablierte sich die Assoziation zur Schlange, was sich unter anderem in der Programmiersprache Cobra[16] sowie dem Python-Toolkit „Boa“[17] äußert. Die erste Vollversion erschien im Januar 1994 unter der Bezeichnung Python 1.0. Gegenüber früheren Versionen wurden einige Konzepte der funktionalen Programmierung implementiert, die allerdings später wieder aufgegeben wurden.[18] Von 1995 bis 2000 erschienen neue Versionen, die fortlaufend als Python 1.1, 1.2 etc. bezeichnet wurden."
    deps:
      - src/stages/load_llm.py
      - ./data/models/llama2-qa-fine-tuned
    params:
      - load_llm
